# Generated by Django 4.1 on 2022-09-29 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_products',
            name='product_price',
            field=models.TextField(db_column='product_price', default=1),
            preserve_default=False,
        ),
    ]
