# Generated by Django 4.1 on 2022-09-30 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_app', '0002_all_products_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_first_name', models.CharField(db_column='customer_first_name', max_length=10)),
                ('customer_last_name', models.CharField(db_column='customer_last_name', max_length=10)),
                ('customer_building_id', models.CharField(db_column='customer_building_id', max_length=20)),
                ('customer_landmark', models.CharField(db_column='customer_landmark', max_length=20)),
                ('customer_street', models.CharField(db_column='customer_street', max_length=20)),
                ('customer_city', models.CharField(db_column='customer_city', max_length=20)),
                ('customer_country', models.CharField(db_column='customer_country', max_length=20)),
                ('customer_pincode', models.CharField(db_column='customer_pincode', max_length=20)),
            ],
        ),
    ]
