# Generated by Django 4.1 on 2022-09-30 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_app', '0003_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='customer_username',
        ),
    ]
