# Generated by Django 4.1 on 2022-09-30 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_app', '0005_remove_customer_customer_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='customer_email',
            field=models.CharField(db_column='customer_email', default='1', max_length=20),
            preserve_default=False,
        ),
    ]
