# Generated by Django 4.1 on 2022-10-02 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_app', '0007_subcategory_all_products_product_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='all_products',
            name='product_mrp',
        ),
        migrations.AlterField(
            model_name='all_products',
            name='product_arrival_time',
            field=models.DateField(db_column='product_arrival_time'),
        ),
        migrations.AlterField(
            model_name='all_products',
            name='product_price',
            field=models.IntegerField(db_column='product_price'),
        ),
    ]
