# Generated by Django 4.1 on 2022-10-02 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_app', '0008_remove_all_products_product_mrp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_products',
            name='product_arrival_time',
            field=models.TextField(db_column='product_arrival_time'),
        ),
    ]
